# Exam on Convolutional Neural Networks (CNN)

Welcome to the Convolutional Neural Networks (CNN) practical exam. In this exam, you will work on an image classification task to predict weather the parkinglot is occupied or empty. You are provided with a dataset of parkinglot images, and your task is to build, train, and evaluate a CNN model.

---

## Dataset Overview
### **Dataset:**
* Just run the command under the `Load Data` section to get the data downloaded and unzipped or you can access it [here](www.kaggle.com/datasets/khaledzsa/parkinglot-occupation)
### **Dataset Name:** ParkingLot Occupation

### **Description:**  
The dataset contains images of labeld parkinglot images for classification purposes. Each image belongs to one of the 2 classes, representing the label.

### **Labels:**
* `empty`
* `occupied`


## Load Data
Run the following command to get the data and unzip it, alternatively you can access the data [here](www.kaggle.com/datasets/khaledzsa/parkinglot-occupation).

In [48]:
!kaggle datasets download -d khaledzsa/parkinglot-occupation
!unzip parkinglot-occupation.zip

Dataset URL: https://www.kaggle.com/datasets/khaledzsa/parkinglot-occupation
License(s): unknown
parkinglot-occupation.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  parkinglot-occupation.zip
replace ParkingLot_Occupation/test/empty/roi_004a880991fb418298519ca2616f3147_empty.jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

## Import Libraries

In [105]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import os
from PIL import Image

## Data Preprocessing
In this section, preprocess the dataset by:
- Loading the images from the file paths.
- Resizing the images to a consistent size.
- Normalizing pixel values.

Add more if needed!

In [106]:

# Define the paths to the image directories
empty_dir = 'ParkingLot_Occupation/train/empty'
occupied_dir = 'ParkingLot_Occupation/train/occupied'

# Load the images and labels
images = []
labels = []

for filename in os.listdir(empty_dir):
  if filename.endswith('.jpg'):
    img = Image.open(os.path.join(empty_dir, filename))
    images.append(np.array(img))
    labels.append(0)  # 0 for empty

for filename in os.listdir(occupied_dir):
  if filename.endswith('.jpg'):
    img = Image.open(os.path.join(occupied_dir, filename))
    images.append(np.array(img))
    labels.append(1)  # 1 for occupied


In [71]:
images

[array([[[81, 82, 77],
         [79, 80, 75],
         [82, 83, 78],
         ...,
         [92, 93, 88],
         [89, 90, 85],
         [91, 92, 87]],
 
        [[81, 82, 77],
         [81, 82, 77],
         [85, 86, 81],
         ...,
         [87, 88, 83],
         [95, 96, 91],
         [91, 92, 87]],
 
        [[80, 81, 76],
         [80, 81, 76],
         [82, 83, 78],
         ...,
         [95, 96, 91],
         [95, 96, 91],
         [85, 86, 81]],
 
        ...,
 
        [[55, 55, 53],
         [53, 53, 51],
         [67, 67, 65],
         ...,
         [67, 67, 65],
         [67, 67, 65],
         [65, 65, 63]],
 
        [[50, 50, 48],
         [64, 64, 62],
         [59, 59, 57],
         ...,
         [71, 71, 69],
         [71, 71, 69],
         [69, 69, 67]],
 
        [[66, 66, 64],
         [69, 69, 67],
         [62, 62, 60],
         ...,
         [74, 74, 72],
         [71, 71, 69],
         [67, 67, 65]]], dtype=uint8),
 array([[[127, 111,  86],
         [126, 1

In [107]:
img_width, img_height = 128, 128
resized_images = [np.array(Image.fromarray(img).resize((img_width, img_height))) for img in images]


In [108]:
resized_images = np.array(resized_images) / 255.0


## Data Splitting
In this section, we will split our dataset into three parts:

* `train` Folder: Training set (85%).
* `train` Folder: Validation set (15%).
* `test` Folder: Test set (100%).

In [109]:
X_train, X_val, y_train, y_val = train_test_split(resized_images, labels, test_size=0.15, random_state=42)

test_dir = 'ParkingLot_Occupation/test'
X_test = []
y_test = []

for filename in os.listdir(test_dir):
  if filename.endswith('.jpg'):
    img = Image.open(os.path.join(test_dir, filename))
    X_test.append(np.array(img))
    y_test.append(0 if 'empty' in filename else 1)

X_test = np.array([np.array(Image.fromarray(img).resize((img_width, img_height))) for img in X_test]) / 255.0
y_test = np.array(y_test)


## Building the CNN Model
In this section, define the architecture of the CNN model. The architecture may consist of:
- Convolutional layers with max-pooling
- Dropout layers
- Flatten layer
- Dense layers
- Output layer

Add and remove any of these as needed!

In [120]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.summary()
adam_opt = tf.keras.optimizers.Adam(learning_rate=0.01)



/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_53 (Conv2D)                   │ (None, 126, 126, 32)        │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_44 (MaxPooling2D)      │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_54 (Conv2D)                   │ (None, 61, 61, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_45 (MaxPooling2D)      │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_55 (Conv2D)                   │ (None, 28, 28, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_46 (MaxPooling2D)      │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_16 (Flatten)                 │ (None, 25088)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_35 (Dense)                     │ (None, 128)                 │       3,211,392 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_16 (Dropout)                 │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_36 (Dense)                     │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,304,193 (12.60 MB)

 Trainable params: 3,304,193 (12.60 MB)

 Non-trainable params: 0 (0.00 B)

## Training the Model
Train the CNN model using the training data and validate it on the validation set.

In [122]:
model.compile(optimizer=adam_opt, loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))


ValueError: Unrecognized data type: x=[[[[1.        ]
   [1.        ]
   [0.90588235]
   ...
   [0.39215686]
   [0.4       ]
   [0.39215686]]

  [[0.98431373]
   [0.97254902]
   [0.90196078]
   ...
   [0.42352941]
   [0.38039216]
   [0.36078431]]

  [[0.92941176]
   [0.91372549]
   [0.88627451]
   ...
   [0.47843137]
   [0.36470588]
   [0.31764706]]

  ...

  [[0.4745098 ]
   [0.4745098 ]
   [0.4745098 ]
   ...
   [0.00784314]
   [0.00392157]
   [0.00392157]]

  [[0.4745098 ]
   [0.4745098 ]
   [0.4745098 ]
   ...
   [0.00392157]
   [0.        ]
   [0.        ]]

  [[0.4745098 ]
   [0.4745098 ]
   [0.4745098 ]
   ...
   [0.00392157]
   [0.        ]
   [0.        ]]]


 [[[0.14117647]
   [0.14117647]
   [0.14117647]
   ...
   [0.18431373]
   [0.18431373]
   [0.18431373]]

  [[0.1372549 ]
   [0.1372549 ]
   [0.1372549 ]
   ...
   [0.18823529]
   [0.18823529]
   [0.18823529]]

  [[0.12941176]
   [0.12941176]
   [0.12941176]
   ...
   [0.18823529]
   [0.18823529]
   [0.18823529]]

  ...

  [[0.34509804]
   [0.34509804]
   [0.34509804]
   ...
   [0.34117647]
   [0.34117647]
   [0.34117647]]

  [[0.35686275]
   [0.35686275]
   [0.35686275]
   ...
   [0.34117647]
   [0.34117647]
   [0.34117647]]

  [[0.36078431]
   [0.35686275]
   [0.35686275]
   ...
   [0.34509804]
   [0.34509804]
   [0.34509804]]]


 [[[0.23921569]
   [0.22352941]
   [0.2       ]
   ...
   [0.27843137]
   [0.27058824]
   [0.2627451 ]]

  [[0.23921569]
   [0.22352941]
   [0.2       ]
   ...
   [0.27843137]
   [0.27058824]
   [0.26666667]]

  [[0.24313725]
   [0.22745098]
   [0.20392157]
   ...
   [0.27843137]
   [0.27843137]
   [0.27843137]]

  ...

  [[0.13333333]
   [0.1372549 ]
   [0.14117647]
   ...
   [0.97254902]
   [0.96862745]
   [0.97254902]]

  [[0.12941176]
   [0.1372549 ]
   [0.15294118]
   ...
   [0.95686275]
   [0.95294118]
   [0.95686275]]

  [[0.1254902 ]
   [0.1372549 ]
   [0.15686275]
   ...
   [0.94901961]
   [0.94901961]
   [0.95294118]]]


 ...


 [[[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  ...

  [[0.00392157]
   [0.00392157]
   [0.00392157]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.        ]
   [0.        ]
   ...
   [0.        ]
   [0.        ]
   [0.        ]]]


 [[[0.35294118]
   [0.34509804]
   [0.32941176]
   ...
   [0.47843137]
   [0.47058824]
   [0.46666667]]

  [[0.34901961]
   [0.34117647]
   [0.3254902 ]
   ...
   [0.47843137]
   [0.47058824]
   [0.46666667]]

  [[0.33333333]
   [0.32941176]
   [0.31764706]
   ...
   [0.46666667]
   [0.4627451 ]
   [0.45882353]]

  ...

  [[0.36470588]
   [0.36470588]
   [0.36078431]
   ...
   [0.31372549]
   [0.31764706]
   [0.31764706]]

  [[0.36862745]
   [0.36862745]
   [0.36470588]
   ...
   [0.31764706]
   [0.32156863]
   [0.3254902 ]]

  [[0.37254902]
   [0.37254902]
   [0.37254902]
   ...
   [0.3254902 ]
   [0.32941176]
   [0.32941176]]]


 [[[0.46666667]
   [0.47058824]
   [0.4745098 ]
   ...
   [0.49803922]
   [0.49019608]
   [0.48627451]]

  [[0.47843137]
   [0.47843137]
   [0.47843137]
   ...
   [0.49803922]
   [0.49019608]
   [0.49019608]]

  [[0.48235294]
   [0.48235294]
   [0.4745098 ]
   ...
   [0.49019608]
   [0.49411765]
   [0.49411765]]

  ...

  [[0.5372549 ]
   [0.5372549 ]
   [0.52941176]
   ...
   [0.50980392]
   [0.51372549]
   [0.51372549]]

  [[0.53333333]
   [0.53333333]
   [0.5254902 ]
   ...
   [0.50588235]
   [0.50196078]
   [0.50196078]]

  [[0.5372549 ]
   [0.5372549 ]
   [0.53333333]
   ...
   [0.50588235]
   [0.50980392]
   [0.51372549]]]] (of type <class 'numpy.ndarray'>)

## Evaluate the Model
Evaluate the performance of the model on the test set.

In [113]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)


ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("IteratorGetNext:0", shape=(32,), dtype=float32). Expected shape (None, 128, 128, 1), but input has incompatible shape (32,)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(32,), dtype=float32)
  • training=False
  • mask=None

## Make Predictions
Use the trained model to make predictions on new or unseen parkinglot images.

if you need new, we prepared some data for you [here](www.kaggle.com/datasets/khaledzsa/parkinglot-occupation), or you can simply run the following command to get the data and unzip it.

<small>Note: please note that the file contain MetaData to tell you what each image contains <b>THIS IS JUST FOR YOU TO MAKE SURE</b></smmall>

If you ran the command above, you should have a file called ParkingLot_Occupation in your current directory. which contains the testing dataset.
If you ran the command above <span style='color:red;'>DON'T RUN THIS CELL</span>

In [ ]:
!kaggle datasets download -d khaledzsa/parkinglot-occupation
!unzip parkinglot-occupation.zip

In [ ]:

predictions = model.predict(X_test)
predicted_labels = np.argmax(predictions, axis=1)
print(predicted_labels)


## Model Performance Visualization
Visualize performance metrics such as accuracy and loss over the epochs.

In [ ]:
# Plot the training and validation accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# Plot the training and validation loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['Train', 'Validation'], loc='upper right')
plt.show()


## Save the Model
Save the trained CNN model for submission.

In [ ]:
model.save("my_model.h5")

## Project Questions:

1. **Data Preprocessing**: Explain why you chose your specific data preprocessing techniques (e.g., resizing images, normalization, data augmentation). How do these preprocessing steps improve the performance of your CNN model?
2. **Model Architecture**: Describe the architecture of your CNN model (e.g., number of convolutional layers, kernel sizes, pooling layers). Why did you choose this structure, and how do you expect each layer to contribute to feature extraction?
3. **Activation Functions**: Justify your choice of activation functions. How do they influence the training and output of your CNN?
4. **Training Process**: Discuss your choice of batch size, number of epochs, and optimizer. How did these decisions impact the training process and the convergence of the model?
5. **Loss Function and Metrics**: Explain why you chose the specific loss function and evaluation metrics for this classification task. How do they align with the goal of correctly classifying parkinglot?
6. **Regularization Techniques**: If you used regularization methods like dropout or batch normalization, explain why you implemented them and how they helped prevent overfitting in your model.
7. **Model Evaluation**: Justify the method you used to evaluate your model's performance on the test set. Why did you select these evaluation techniques, and what insights did they provide about your model's accuracy and generalization ability?
8. **Model Visualization**: Explain the significance of the performance visualizations (e.g., accuracy and loss curves). What do they tell you about your model's training process and its ability to generalize?
9. **Overfitting and Underfitting**: Analyze whether the model encountered any overfitting or underfitting during training. What strategies could you implement to mitigate these issues?

### Answer Here:

All my answers depends on succsessing the train step.
Unfortunatlly, for some error the train doesn't executed ☹